use_syn: False
use_benchmark: True
resolution: 512
bs_per_gpu: 6 # OOM for 8xGPUs
masked_training: True
uniform_yaw: True
pretrain_just_disabled: True
autobackup_hour: 1
write_preview_history: False
random_flip: False
face_type: wf
models_opt_on_gpu: False
archi: liae-ud
ae_dims: 256
e_dims: 256
d_dims: 160
d_mask_dims: 22
eyes_prio: False
lr_dropout: False
random_warp: False
gan_power: 1.0
true_face_power: 0.0
face_style_power: 0.0
bg_style_power: 0.0
ct_mode: none
clipgrad: False
pretrain: False
