use_syn: False
use_benchmark: True
resolution: 128
masked_training: False
uniform_yaw: False
pretrain_just_disabled: True
autobackup_hour: 1
write_preview_history: True
random_flip: False
face_type: wf
models_opt_on_gpu: True
archi: df
ae_dims: 64
e_dims: 32
d_dims: 32
d_mask_dims: 22
eyes_prio: False
lr_dropout: False
random_warp: False
gan_power: 0.0
true_face_power: 0.0
face_style_power: 0.0
bg_style_power: 0.0
ct_mode: none
clipgrad: False
pretrain: False
