use_syn: False
use_benchmark: True
resolution: 416
masked_training: True
uniform_yaw: True
pretrain_just_disabled: True
autobackup_hour: 1
write_preview_history: True
random_flip: False
face_type: wf
models_opt_on_gpu: False
archi: liae-ud
ae_dims: 288
e_dims: 168
d_dims: 120
d_mask_dims: 22
eyes_prio: False
lr_dropout: False
random_warp: False
gan_power: 0.0
true_face_power: 0.0
face_style_power: 0.0
bg_style_power: 0.0
ct_mode: none
clipgrad: False
pretrain: False
