use_syn: False
use_benchmark: True
resolution: 128
bs_per_gpu: 32
masked_training: True
uniform_yaw: False
pretrain_just_disabled: True
autobackup_hour: 1
write_preview_history: False
random_flip: False
face_type: wf
models_opt_on_gpu: False
archi: liae
ae_dims: 128
e_dims: 64
d_dims: 64
d_mask_dims: 64
eyes_prio: False
lr_dropout: False
random_warp: False
gan_power: 0.0
true_face_power: 0.0
face_style_power: 0.1
bg_style_power: 0.0
ct_mode: none
clipgrad: False
pretrain: False
